implementing glm_test;
import glm;

public float2 test_float2(float2 v)
{
    return v;
}

public float3 test_float3(float3 v)
{
    return v;
}

public float4 test_float4(float4 v)
{
    return v;
}

public float2x2 test_float2x2(float2x2 m)
{
    return m;
}

public float3x3 test_float3x3(float3x3 m)
{
    return m;
}

public float4x4 test_float4x4(float4x4 m)
{
    return m;
}

public glm.quat.quat test_quaternion(glm.quat.quat q)
{
    return q;
}
